# Veri hakkında bilgi

In [2]:
#### Veri seti okuma #####
import pandas as pd
veriseti = pd.read_excel("/Users/sdrttnclskn/Desktop/tez/tez-calismasi/tez_uygulama/veri_seti.xlsx")
df = veriseti.copy()
df.head()

,TARIH,FONTIP,FONTUR,FON,Unnamed: 4,FONTOPLAMDEGER,TEDAVPAYSAYISI,KISISAYISI,FONFIYAT,FAIZ,...,TR,TPP,T,VM,VDM,YBA,YHS,YMK,D,R
0,2019-01-02,BORSA YATIRIM FONU,Altın Fonu,FGA,NaN,8.722176e+07,4.350000e+06,0,20.050979,0.2302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-02,BORSA YATIRIM FONU,Gümüş Fonu,FGS,NaN,1.238294e+07,7.000000e+05,0,17.689916,0.2302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-02,BORSA YATIRIM FONU,Hisse Senedi Fonu,DJA,NaN,1.491130e+07,4.800000e+05,0,31.065216,0.2302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-02,EMEKLİLİK FONU,Altın Fonu,AEA,NaN,1.465104e+09,6.335717e+10,325392,0.023125,0.2302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-02,EMEKLİLİK FONU,Altın Fonu,AEL,NaN,1.784293e+09,7.415738e+10,325460,0.024061,0.2302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.info();

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187438 entries, 0 to 187437
Data columns (total 38 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   TARIH           187438 non-null  datetime64[ns]
 1   FONTIP          187438 non-null  object
 2   FONTUR          187438 non-null  object
 3   FON             187438 non-null  object
 4   Unnamed: 4      0 non-null       float64
 5   FONTOPLAMDEGER  187438 non-null  float64
 6   TEDAVPAYSAYISI  187438 non-null  float64
 7   KISISAYISI      187438 non-null  int64
 8   FONFIYAT        187438 non-null  float64
 9   FAIZ            187438 non-null  float64
 10  DOLARFIYAT      187438 non-null  float64
 11  ALTINFIYAT      187438 non-null  float64
 12  BB              187438 non-null  float64
 13  DT              185256 non-null  float64
 14  DB              173992 non-null  float64
 15  DÖT             148075 non-null  float64
 16  EUT             113791 non-null  float64
 17  FB              84322 non-null   float64
 18  FKB             55378 non-null   float64
 19  GAS             34803 non-null   float64
 20  HB              21222 non-null   float64
 21  HS              11863 non-null   float64
 22  KBA             6322 non-null    float64
 23  KKS             2693 non-null    float64
 24  KH              1216 non-null    float64
 25  KM              548 non-null     float64
 26  OSKS            211 non-null     float64
 27  OST             11 non-null      float64
 28  TR              0 non-null       float64
 29  TPP             0 non-null       float64
 30  T               0 non-null       float64
 31  VM              0 non-null       float64
 32  VDM             0 non-null       float64
 33  YBA             0 non-null       float64
 34  YHS             0 non-null       float64
 35  YMK             0 non-null       float64
 36  D               0 non-null       float64
 37  R               0 non-null       float64
dtypes: datetime64[ns](1), float64(33), int64(1), object(3)
memory usage: 54.3+ MB

In [6]:
df.isnull().values.any()

True

In [7]:
df.isnull().sum()

TARIH                  0
FONTIP                 0
FONTUR                 0
FON                    0
Unnamed: 4        187438
FONTOPLAMDEGER         0
TEDAVPAYSAYISI         0
KISISAYISI             0
FONFIYAT               0
FAIZ                   0
DOLARFIYAT             0
ALTINFIYAT             0
BB                     0
DT                  2182
DB                 13446
DÖT                39363
EUT                73647
FB                103116
FKB               132060
GAS               152635
HB                166216
HS                175575
KBA               181116
KKS               184745
KH                186222
KM                186890
OSKS              187227
OST               187427
TR                187438
TPP               187438
T                 187438
VM                187438
VDM               187438
YBA               187438
YHS               187438
YMK               187438
D                 187438
R                 187438
dtype: int64

In [8]:
df.tail()

,TARIH,FONTIP,FONTUR,FON,Unnamed: 4,FONTOPLAMDEGER,TEDAVPAYSAYISI,KISISAYISI,FONFIYAT,FAIZ,...,TR,TPP,T,VM,VDM,YBA,YHS,YMK,D,R
187433,2019-12-31,YATIRIM FONU,Serbest Fon,UPD,NaN,5.113163e+07,24459866.0,105,2.090430,0.1138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187434,2019-12-31,YATIRIM FONU,Serbest Fon,UPS,NaN,1.547605e+07,2401832.0,1,6.443434,0.1138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187435,2019-12-31,YATIRIM FONU,Serbest Fon,UPU,NaN,1.054165e+06,573729.0,2,1.837393,0.1138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187436,2019-12-31,YATIRIM FONU,Serbest Fon,USY,NaN,8.851681e+06,441725675.0,1,0.020039,0.1138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187437,2019-12-31,YATIRIM FONU,Serbest Fon,ZPA,NaN,5.204444e+08,351412827.0,1,1.481006,0.1138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FONTOPLAMDEGER,187438.0,2.394037e+08,5.509213e+08,0.000000,6.929778e+06,3.815812e+07,1.786791e+08,7.207539e+09
TEDAVPAYSAYISI,187438.0,6.301665e+09,1.704090e+10,0.000000,3.456783e+07,5.147614e+08,4.347861e+09,2.577214e+11
KISISAYISI,187438.0,4.325684e+04,1.049055e+05,0.000000,5.100000e+01,1.269000e+03,3.306150e+04,1.064438e+06
FONFIYAT,187438.0,3.982973e+00,2.395512e+01,0.000000,1.523725e-02,3.057850e-02,5.684475e-01,3.657033e+02
FAIZ,187438.0,2.034597e-01,4.610195e-02,0.105100,1.630000e-01,2.295000e-01,2.418000e-01,2.550000e-01
DOLARFIYAT,187438.0,5.683442e+00,2.214480e-01,5.203800,5.532600e+00,5.723800e+00,5.813300e+00,6.213800e+00
ALTINFIYAT,187438.0,2.527867e+05,2.080213e+04,216132.634958,2.323975e+05,2.559016e+05,2.715878e+05,2.868514e+05
BB,187438.0,4.071823e+01,3.596555e+01,-90.330000,7.260000e+00,2.794000e+01,7.994000e+01,2.195700e+02
DT,185256.0,2.322606e+01,2.809720e+01,-119.570000,3.110000e+00,9.880000e+00,3.459000e+01,1.074500e+02
DB,173992.0,1.611707e+01,2.267205e+01,-16.150000,1.320000e+00,6.305000e+00,2.011000e+01,1.561000e+02
DÖT,148075.0,1.074313e+01,1.589276e+01,-23.390000,5.900000e-01,4.250000e+00,1.330000e+01,1.000500e+02
EUT,113791.0,9.675534e+00,1.532893e+01,-83.930000,3.500000e-01,3.780000e+00,1.094000e+01,9.918000e+01
FB,84322.0,7.198578e+00,1.222286e+01,-16.570000,5.000000e-02,2.550000e+00,8.520000e+00,9.824000e+01
FKB,55378.0,5.469915e+00,8.954112e+00,-40.620000,2.200000e-01,2.420000e+00,7.540000e+00,9.756000e+01
GAS,34803.0,5.630878e+00,9.449738e+00,-17.890000,2.700000e-01,2.400000e+00,7.140000e+00,9.670000e+01
HB,21222.0,5.858411e+00,8.966694e+00,-15.650000,2.900000e-01,2.540000e+00,7.940000e+00,5.857000e+01
HS,11863.0,4.826362e+00,7.285263e+00,-16.250000,6.000000e-02,1.740000e+00,5.955000e+00,4.899000e+01
KBA,6322.0,2.989703e+00,4.186427e+00,-16.760000,2.600000e-01,1.140000e+00,3.957500e+00,2.425000e+01
KKS,2693.0,2.067130e+00,3.712078e+00,-12.150000,0.000000e+00,9.900000e-01,2.040000e+00,3.756000e+01
KH,1216.0,8.276974e-01,1.394152e+00,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,6.530000e+00
KM,548.0,9.020803e-01,1.827302e+00,0.000000,0.000000e+00,0.000000e+00,1.040000e+00,6.940000e+00
OSKS,211.0,4.872038e-02,2.084678e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
OST,11.0,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
TR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TPP,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
T,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VM,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VDM,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YBA,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YHS,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YMK,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
R,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
## her bir kolon için unique veri sayısı
uniq_data={}
for col in df:
    uniq_data[col] = df[col].unique()
uniq_data

In [19]:
df['FON'].nunique()

892

In [ ]:
from IPython.display import HTML, display


display(HTML(
   '<table><tr>{}</tr></table>'.format(
       '</tr><tr>'.join(
           '<td>{}</td>'.format('</td><td>'.join(str(_) for _ in row)) for row in df)
       )
))